image: python:3.8

variables:
  WORK_DIR: .
cache:
  key: "$CI_COMMIT_REF_SLUG"
stages:
  - deploy
Deploy:
  stage: deploy
  only:
    - master
  tags:
    - team-12-runner
  script:
    - docker-compose down
    - docker-compose build
    - docker-compose up
  variables:
    GIT_STRATEGY: none
