image: python:3.9

variables:
  WORK_DIR: .
cache:
  key: "$CI_COMMIT_REF_SLUG"
stages:
  - deploy
Deploy:
  stage: deploy
  only:
    - master
  tags:
    - team-12-runner
  script:
    - docker-compose stop $(docker ps -aq) || true
    - docker system prune -af --volumes #필요 없는 이미지, 컨테이너 제거
    - docker-compose build -t docker-test 
    - docker-compose run -d -p 5000:5000 docker-test
