image: python:3.8

variables:
  WORK_DIR: .
cache:
  key: "$CI_COMMIT_REF_SLUG"
stages:
  - deploy
Deploy:
  stage: deploy
  only:
    - master
  tags:
    - team-12-runner
  script:
    - sudo chmod u+w data/mysql/db/account
    - echo "SELECT 'docker stop';" |docker stop $(docker ps -aq) || true
    - echo "SELECT 'delete old container';" |docker system prune -af --volumes #필요 없는 이미지, 컨테이너 제거
    - echo "SELECT 'docker-compose build';" |docker-compose build    
    - echo "SELECT 'chmod';" |sudo chmod 777 ./data/mysql/db
    - echo "SELECT 'docker-compose up';" |docker-compose run -d -p server
