image: python:3.8

variables:
        IMAGE_VERSION: v1.0.0
        WORK_DIR: . 
        NODE_ENV: development
        DOCKER_DRIVER: overlay2 
        COMPOSE_FILE: "docker-compose.yml:docker-compose.gitlab-ci.yml" 
        DOCKER_BUILD_CONTEXT: . 
        DOCKER_IMAGE: fullstack-recommender:${IMAGE_VERSION}
cache:
        key: "$CI_COMMIT_REF_SLUG" 
stages:
        - deploy
Deploy: 
        stage: deploy 
        only: 
                - master
        tags: 
                - team-12-runner 
        script:
                - docker-compose stop ${docker ps -aq} || true 
                - docker-compose build -t team-12-backend . 
                - docker-compose run -p 8080:80 team-12-backend 

