image: python:3.8

test-job:
  stages:
  - test

  before_script:
    - apk update
    - apk upgrade
    - apk add make

  test:
    stage: test
    image: tiangolo/docker-with-compose:latest
    services:
    - docker:dind
    tags: [test]
    script:
      - make prod-up # docker-compose up -d --build
      - make composer-init-dev
      - make test

deploy-prod:
  variables:
    WORK_DIR: .
  cache:
    key: "$CI_COMMIT_REF_SLUG"
  stages:
    - deploy
  Deploy:
    stage: deploy
    only:
      - master
    tags:
      - team-12-runner
    script:
      - sudo service docker start
      - docker-compose stop server 
      - docker system prune -af --volumes #필요 없는 이미지, 컨테이너 제거
      - docker-compose build
      - docker-compose run -d -p 5000:5000 server
    variables:
      GIT_STRATEGY: none
