image: python:3.8

variables:
  WORK_DIR: .
cache:
  key: "$CI_COMMIT_REF_SLUG"
stages:
  - deploy
Deploy:
  stage: deploy
  only:
    - master
  tags:
    - team-12-runner
  before_script:
    - sudo ls -la /var/run/docker.sock
    - sudo usermod -aG docker ${USER}
  script:
    - docker-compose down
    - docker system prune -af --volumes #필요 없는 이미지, 컨테이너 제거
    - docker-compose build
    - docker-compose up
  variables:
    GIT_STRATEGY: none
