image: python:3.8

variables:
  WORK_DIR: .
cache:
  key: "$CI_COMMIT_REF_SLUG"
stages:
  - deploy
Deploy:
  stage: deploy
  only:
    - master
  tags:
    - team-12-runner
  before_script: 
    - apt install net-tools
  script:
    - docker stop $(docker ps -aq) || true
    - docker system prune -af --volumes #필요 없는 이미지, 컨테이너 제거
    - docker-compose build
    - docker-compose ps 
    - docker-compose run -d --service-ports server
    - netstat -a 
    - netstat -nap | grep 8000
    - docker-compose run -d -p 8000:8000 server
    - netstat -nap | grep 8000
  variables:
    GIT_STRATEGY: none

