image: python:3.8

variables:
  WORK_DIR: .
cache:
  key: "$CI_COMMIT_REF_SLUG"
stages:
  - deploy
Deploy:
  stage: deploy
  only:
    - master
  tags:
    - team-12-runner
  script:
    - sudo docker-compose stop server 
    - sudo docker system prune -af --volumes #필요 없는 이미지, 컨테이너 제거
    - sudo docker-compose build
    - sudo docker-compose run -d -p 5000:5000 server
  variables:
    GIT_STRATEGY: none
