version: "3"
services:
  client:
    container_name: client
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    command: npm start
    restart: always
    # environment:
    #   - NODE_ENV=development
    # stdin_open: true
    # tty: true

  server:
    container_name: server
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    image: server:apps
    command: python manage.py runserver 0.0.0.0:5000
    restart: always
