version: "3"
services:
  client:
    container_name: client
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ".:/apps"
      - "/apps/node_modules"
    ports:
      - "3000:3000"
    restart: always
    command: npm start
    depends_on:
      - client
    # environment:
    #   - NODE_ENV=development
    # stdin_open: true
    # tty: true

  server:
    container_name: server
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/apps
    ports:
      - "5000:5000"
    image: server:apps
    command: python manage.py runserver 0.0.0.0:5000
    restart: always
