version: "3"
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: "django-app-db"
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    volumes:
      - ./data/mysql/db:/var/lib/mysql

  server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./backend:/apps
    ports:
      - "8000:8000"
    image: server:apps
    container_name: django_container
    command: python manage.py runserver
    depends_on:
      - db
